/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Leopoldo
 */
public class CadastroView extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cadastro
     */
    public CadastroView() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLocalização = new javax.swing.JPanel();
        cbxSala = new javax.swing.JComboBox<>();
        cbxPiso = new javax.swing.JComboBox<>();
        cbxBloco = new javax.swing.JComboBox<>();
        cbxUnidade = new javax.swing.JComboBox<>();
        tfdEmail = new javax.swing.JTextField();
        lblUnidade = new javax.swing.JLabel();
        lblNomeUnidade = new javax.swing.JLabel();
        tfdNomeUnidade = new javax.swing.JTextField();
        lblTelefoneUnidade = new javax.swing.JLabel();
        tfdTelefoneUnidade = new javax.swing.JTextField();
        lblEnderecoUnidade = new javax.swing.JLabel();
        tfdEnderecoUnidade = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        btnCadastrarUnidade = new javax.swing.JButton();
        lblRespostaUnidade = new javax.swing.JLabel();
        btnPiso = new javax.swing.JButton();
        lblRespostaPiso = new javax.swing.JLabel();
        lblSala = new javax.swing.JLabel();
        lblBloco = new javax.swing.JLabel();
        lblDescricaoSala = new javax.swing.JLabel();
        lblDescricaoBloco = new javax.swing.JLabel();
        tfdDescricaoSala = new javax.swing.JTextField();
        tfdDescricaoBloco = new javax.swing.JTextField();
        btnSala = new javax.swing.JButton();
        btnBloco = new javax.swing.JButton();
        lblRespostaSala = new javax.swing.JLabel();
        lblRespostaBloco = new javax.swing.JLabel();
        sprBlocoPiso = new javax.swing.JSeparator();
        lblPiso = new javax.swing.JLabel();
        sprPisoSala = new javax.swing.JSeparator();
        lblDescricaoPiso = new javax.swing.JLabel();
        tfdDescricaoPiso = new javax.swing.JTextField();
        pnlCadastroTipo = new javax.swing.JPanel();
        pnlCadastroTipoSubtipo = new javax.swing.JPanel();
        lblTipo = new javax.swing.JLabel();
        lblDescricaoTipo = new javax.swing.JLabel();
        tfDescricaoTipo = new javax.swing.JTextField();
        btnTipo = new javax.swing.JButton();
        lblRespostaTipo = new javax.swing.JLabel();
        lblSubtipo = new javax.swing.JLabel();
        lblDescricaoSubtipo = new javax.swing.JLabel();
        tfDescricaoPiso1 = new javax.swing.JTextField();
        btnPiso1 = new javax.swing.JButton();
        lblRespostaPiso1 = new javax.swing.JLabel();
        Separador3 = new javax.swing.JSeparator();
        cbxSubtipo = new javax.swing.JComboBox<>();
        cbxTipo = new javax.swing.JComboBox<>();
        pnlPatrimonio = new javax.swing.JPanel();
        lblPatrimonio = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        tfdCodigo = new javax.swing.JTextField();
        lblDescricao = new javax.swing.JLabel();
        tfdDescricao = new javax.swing.JTextField();
        lblGrauConservacao = new javax.swing.JLabel();
        sldGrauConservacao = new javax.swing.JSlider();
        lblStatus = new javax.swing.JLabel();
        rbnStatus1 = new javax.swing.JRadioButton();
        rbnStatus2 = new javax.swing.JRadioButton();
        lblNotaFiscal = new javax.swing.JLabel();
        tfdNotaFiscal = new javax.swing.JTextField();
        lblOrgao = new javax.swing.JLabel();
        cbxOrgao = new javax.swing.JComboBox<>();
        btnCadastrar = new javax.swing.JButton();
        lblResposta = new javax.swing.JLabel();
        cbxUnidade1 = new javax.swing.JComboBox<>();
        cbxBloco1 = new javax.swing.JComboBox<>();
        cbxPiso1 = new javax.swing.JComboBox<>();
        cbxSala1 = new javax.swing.JComboBox<>();
        cbxSuptipo = new javax.swing.JComboBox<>();
        cbxTipo1 = new javax.swing.JComboBox<>();
        speBusca = new javax.swing.JScrollPane();
        tblBusca = new javax.swing.JTable();

        setName(""); // NOI18N

        cbxSala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sala 1", "Cadastrar Sala" }));

        cbxPiso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Piso 1", "Cadastrar Piso" }));

        cbxBloco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bloco A", "Cadastrar Bloco" }));
        cbxBloco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxBlocoActionPerformed(evt);
            }
        });

        cbxUnidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UEMG", "Cadastrar Unidade" }));

        lblUnidade.setText("UNIDADE");

        lblNomeUnidade.setText("Nome ");

        lblTelefoneUnidade.setText("Telefone ");

        lblEnderecoUnidade.setText("Endereço");

        lblEmail.setText("E-mail");

        btnCadastrarUnidade.setText("Cadastrar");

        lblRespostaUnidade.setText("Mensagem Resposta");

        btnPiso.setText("Cadastrar");

        lblRespostaPiso.setText("Mensagem Resposta");

        lblSala.setText("SALA");

        lblBloco.setText("BLOCO");

        lblDescricaoSala.setText("Descrição");

        lblDescricaoBloco.setText("Descrição");

        btnSala.setText("Cadastrar");

        btnBloco.setText("Cadastrar");

        lblRespostaSala.setText("Mensagem Resposta");

        lblRespostaBloco.setText("Mensagem Resposta");

        lblPiso.setText("PISO");

        lblDescricaoPiso.setText("Descrição");

        lblTipo.setText("TIPO");

        lblDescricaoTipo.setText("Descrição");

        btnTipo.setText("Cadastrar");

        lblRespostaTipo.setText("Mensagem Resposta");

        lblSubtipo.setText("SUBTIPO");

        lblDescricaoSubtipo.setText("Descrição");

        btnPiso1.setText("Cadastrar");

        lblRespostaPiso1.setText("Mensagem Resposta");

        javax.swing.GroupLayout pnlCadastroTipoSubtipoLayout = new javax.swing.GroupLayout(pnlCadastroTipoSubtipo);
        pnlCadastroTipoSubtipo.setLayout(pnlCadastroTipoSubtipoLayout);
        pnlCadastroTipoSubtipoLayout.setHorizontalGroup(
            pnlCadastroTipoSubtipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroTipoSubtipoLayout.createSequentialGroup()
                .addGroup(pnlCadastroTipoSubtipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastroTipoSubtipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCadastroTipoSubtipoLayout.createSequentialGroup()
                            .addGap(111, 111, 111)
                            .addComponent(lblTipo))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCadastroTipoSubtipoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(pnlCadastroTipoSubtipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnlCadastroTipoSubtipoLayout.createSequentialGroup()
                                    .addComponent(lblRespostaTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnTipo))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCadastroTipoSubtipoLayout.createSequentialGroup()
                                    .addComponent(lblDescricaoTipo)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(tfDescricaoTipo, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCadastroTipoSubtipoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(pnlCadastroTipoSubtipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblDescricaoSubtipo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlCadastroTipoSubtipoLayout.createSequentialGroup()
                                    .addComponent(lblRespostaPiso1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnPiso1))
                                .addComponent(tfDescricaoPiso1)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCadastroTipoSubtipoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(Separador3)))
                    .addGroup(pnlCadastroTipoSubtipoLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(lblSubtipo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCadastroTipoSubtipoLayout.setVerticalGroup(
            pnlCadastroTipoSubtipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroTipoSubtipoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDescricaoTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfDescricaoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadastroTipoSubtipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTipo)
                    .addComponent(lblRespostaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(Separador3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSubtipo)
                .addGap(2, 2, 2)
                .addComponent(lblDescricaoSubtipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfDescricaoPiso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadastroTipoSubtipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPiso1)
                    .addComponent(lblRespostaPiso1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        cbxSubtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cadeira", "Cadastrar Subtipo" }));

        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mobilia", "Cadastrar Tipo" }));

        javax.swing.GroupLayout pnlCadastroTipoLayout = new javax.swing.GroupLayout(pnlCadastroTipo);
        pnlCadastroTipo.setLayout(pnlCadastroTipoLayout);
        pnlCadastroTipoLayout.setHorizontalGroup(
            pnlCadastroTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastroTipoLayout.createSequentialGroup()
                .addGroup(pnlCadastroTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxSubtipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlCadastroTipoSubtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlCadastroTipoLayout.setVerticalGroup(
            pnlCadastroTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroTipoLayout.createSequentialGroup()
                .addGroup(pnlCadastroTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastroTipoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlCadastroTipoSubtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCadastroTipoLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxSubtipo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlLocalizaçãoLayout = new javax.swing.GroupLayout(pnlLocalização);
        pnlLocalização.setLayout(pnlLocalizaçãoLayout);
        pnlLocalizaçãoLayout.setHorizontalGroup(
            pnlLocalizaçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLocalizaçãoLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnlLocalizaçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxPiso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxSala, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxBloco, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(pnlLocalizaçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLocalizaçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblTelefoneUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblEnderecoUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlLocalizaçãoLayout.createSequentialGroup()
                            .addComponent(lblRespostaUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCadastrarUnidade))
                        .addComponent(tfdEnderecoUnidade)
                        .addComponent(tfdTelefoneUnidade)
                        .addComponent(tfdNomeUnidade)
                        .addComponent(lblEmail)
                        .addComponent(tfdEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNomeUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLocalizaçãoLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(lblUnidade)))
                .addGap(33, 33, 33)
                .addGroup(pnlLocalizaçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlLocalizaçãoLayout.createSequentialGroup()
                        .addComponent(lblRespostaBloco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBloco))
                    .addComponent(tfdDescricaoBloco, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLocalizaçãoLayout.createSequentialGroup()
                        .addComponent(lblRespostaSala, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSala))
                    .addComponent(tfdDescricaoSala, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLocalizaçãoLayout.createSequentialGroup()
                        .addComponent(lblRespostaPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPiso))
                    .addComponent(tfdDescricaoPiso)
                    .addComponent(sprBlocoPiso, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlLocalizaçãoLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(lblBloco))
                    .addComponent(lblDescricaoBloco, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescricaoSala, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescricaoPiso, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlLocalizaçãoLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(lblPiso))
                    .addComponent(sprPisoSala, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlLocalizaçãoLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(lblSala)))
                .addGap(28, 28, 28)
                .addComponent(pnlCadastroTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLocalizaçãoLayout.setVerticalGroup(
            pnlLocalizaçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLocalizaçãoLayout.createSequentialGroup()
                .addGroup(pnlLocalizaçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLocalizaçãoLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(cbxUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxSala, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLocalizaçãoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNomeUnidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdNomeUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTelefoneUnidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdTelefoneUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEnderecoUnidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdEnderecoUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(pnlLocalizaçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCadastrarUnidade)
                            .addComponent(lblRespostaUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlLocalizaçãoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblBloco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDescricaoBloco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdDescricaoBloco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlLocalizaçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBloco)
                            .addComponent(lblRespostaBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(sprBlocoPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPiso)
                        .addGap(2, 2, 2)
                        .addComponent(lblDescricaoPiso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdDescricaoPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlLocalizaçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPiso)
                            .addComponent(lblRespostaPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(sprPisoSala, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSala)
                        .addGap(7, 7, 7)
                        .addComponent(lblDescricaoSala)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdDescricaoSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlLocalizaçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSala)
                            .addComponent(lblRespostaSala, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pnlCadastroTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblPatrimonio.setText("PATRIMÔNIO");

        lblCodigo.setText("Código");

        lblDescricao.setText("Descrição");

        lblGrauConservacao.setText("Grau de Conservação");

        lblStatus.setText("Status");

        rbnStatus1.setText("jRadioButton1");

        rbnStatus2.setText("jRadioButton2");

        lblNotaFiscal.setText("Nota Fiscal");

        lblOrgao.setText("Orgão");

        cbxOrgao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UEMG" }));

        btnCadastrar.setText("Cadastrar");

        lblResposta.setText("Mensagem Resposta");

        cbxUnidade1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UEMG" }));

        cbxBloco1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bloco A" }));
        cbxBloco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxBloco1ActionPerformed(evt);
            }
        });

        cbxPiso1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Piso 1" }));

        cbxSala1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sala 1" }));
        cbxSala1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSala1ActionPerformed(evt);
            }
        });

        cbxSuptipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cadeira", "Cadastrar Subtipo" }));

        cbxTipo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mobilia", "Cadastrar Tipo" }));

        tblBusca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"UEMG", "Bloco A", "Térreo", "Laboratório II", "Informática", null, "Computador Completo"},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Unidade", "Bloco", "Piso", "Sala", "Tipo", "Subtipo", "Patrimonio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        speBusca.setViewportView(tblBusca);

        javax.swing.GroupLayout pnlPatrimonioLayout = new javax.swing.GroupLayout(pnlPatrimonio);
        pnlPatrimonio.setLayout(pnlPatrimonioLayout);
        pnlPatrimonioLayout.setHorizontalGroup(
            pnlPatrimonioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPatrimonioLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlPatrimonioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxPiso1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxBloco1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxUnidade1, 0, 130, Short.MAX_VALUE)
                    .addComponent(cbxSuptipo, 0, 130, Short.MAX_VALUE)
                    .addComponent(cbxSala1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxTipo1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(69, 69, 69)
                .addGroup(pnlPatrimonioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGrauConservacao)
                    .addComponent(sldGrauConservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus)
                    .addGroup(pnlPatrimonioLayout.createSequentialGroup()
                        .addComponent(rbnStatus1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbnStatus2))
                    .addComponent(tfdNotaFiscal)
                    .addComponent(cbxOrgao, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNotaFiscal)
                    .addGroup(pnlPatrimonioLayout.createSequentialGroup()
                        .addComponent(lblResposta, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastrar))
                    .addGroup(pnlPatrimonioLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(pnlPatrimonioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPatrimonio)
                            .addComponent(lblOrgao)))
                    .addGroup(pnlPatrimonioLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(tfdDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(speBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPatrimonioLayout.setVerticalGroup(
            pnlPatrimonioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPatrimonioLayout.createSequentialGroup()
                .addGroup(pnlPatrimonioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPatrimonioLayout.createSequentialGroup()
                        .addGroup(pnlPatrimonioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPatrimonioLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblPatrimonio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxUnidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxBloco1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxPiso1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(pnlPatrimonioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbxSala1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbnStatus1)
                                    .addComponent(rbnStatus2))
                                .addGap(22, 22, 22)
                                .addComponent(cbxTipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxSuptipo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPatrimonioLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(tfdCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDescricao)
                                .addGap(1, 1, 1)
                                .addComponent(tfdDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblGrauConservacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sldGrauConservacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblStatus)
                                .addGap(35, 35, 35)
                                .addComponent(lblNotaFiscal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfdNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblOrgao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxOrgao, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(pnlPatrimonioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblResposta)
                            .addComponent(btnCadastrar)))
                    .addGroup(pnlPatrimonioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(speBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlLocalização, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlPatrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlLocalização, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPatrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxBlocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxBlocoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxBlocoActionPerformed

    private void cbxBloco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxBloco1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxBloco1ActionPerformed

    private void cbxSala1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSala1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSala1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator Separador3;
    private javax.swing.JButton btnBloco;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCadastrarUnidade;
    private javax.swing.JButton btnPiso;
    private javax.swing.JButton btnPiso1;
    private javax.swing.JButton btnSala;
    private javax.swing.JButton btnTipo;
    private javax.swing.JComboBox<String> cbxBloco;
    private javax.swing.JComboBox<String> cbxBloco1;
    private javax.swing.JComboBox<String> cbxOrgao;
    private javax.swing.JComboBox<String> cbxPiso;
    private javax.swing.JComboBox<String> cbxPiso1;
    private javax.swing.JComboBox<String> cbxSala;
    private javax.swing.JComboBox<String> cbxSala1;
    private javax.swing.JComboBox<String> cbxSubtipo;
    private javax.swing.JComboBox<String> cbxSuptipo;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JComboBox<String> cbxTipo1;
    private javax.swing.JComboBox<String> cbxUnidade;
    private javax.swing.JComboBox<String> cbxUnidade1;
    private javax.swing.JLabel lblBloco;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblDescricaoBloco;
    private javax.swing.JLabel lblDescricaoPiso;
    private javax.swing.JLabel lblDescricaoSala;
    private javax.swing.JLabel lblDescricaoSubtipo;
    private javax.swing.JLabel lblDescricaoTipo;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEnderecoUnidade;
    private javax.swing.JLabel lblGrauConservacao;
    private javax.swing.JLabel lblNomeUnidade;
    private javax.swing.JLabel lblNotaFiscal;
    private javax.swing.JLabel lblOrgao;
    private javax.swing.JLabel lblPatrimonio;
    private javax.swing.JLabel lblPiso;
    private javax.swing.JLabel lblResposta;
    private javax.swing.JLabel lblRespostaBloco;
    private javax.swing.JLabel lblRespostaPiso;
    private javax.swing.JLabel lblRespostaPiso1;
    private javax.swing.JLabel lblRespostaSala;
    private javax.swing.JLabel lblRespostaTipo;
    private javax.swing.JLabel lblRespostaUnidade;
    private javax.swing.JLabel lblSala;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblSubtipo;
    private javax.swing.JLabel lblTelefoneUnidade;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblUnidade;
    private javax.swing.JPanel pnlCadastroTipo;
    private javax.swing.JPanel pnlCadastroTipoSubtipo;
    private javax.swing.JPanel pnlLocalização;
    private javax.swing.JPanel pnlPatrimonio;
    private javax.swing.JRadioButton rbnStatus1;
    private javax.swing.JRadioButton rbnStatus2;
    private javax.swing.JSlider sldGrauConservacao;
    private javax.swing.JScrollPane speBusca;
    private javax.swing.JSeparator sprBlocoPiso;
    private javax.swing.JSeparator sprPisoSala;
    private javax.swing.JTable tblBusca;
    private javax.swing.JTextField tfDescricaoPiso1;
    private javax.swing.JTextField tfDescricaoTipo;
    private javax.swing.JTextField tfdCodigo;
    private javax.swing.JTextField tfdDescricao;
    private javax.swing.JTextField tfdDescricaoBloco;
    private javax.swing.JTextField tfdDescricaoPiso;
    private javax.swing.JTextField tfdDescricaoSala;
    private javax.swing.JTextField tfdEmail;
    private javax.swing.JTextField tfdEnderecoUnidade;
    private javax.swing.JTextField tfdNomeUnidade;
    private javax.swing.JTextField tfdNotaFiscal;
    private javax.swing.JTextField tfdTelefoneUnidade;
    // End of variables declaration//GEN-END:variables
}
