/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.BlocoDAO;
import dao.OrgaoDAO;
import dao.GrauConservacaoDAO;
import dao.PatrimonioCompostoDAO;
import dao.PatrimonioDAO;
import dao.PisoDAO;
import dao.SalaDAO;
import dao.StatusDAO;
import dao.SubTipoDAO;
import dao.TipoDAO;
import dao.UnidadeDAO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.BlocoM;
import model.OrgaoM;
import model.GrauConservacaoM;
import model.PatrimonioCompostoM;
import model.PatrimonioM;
import model.PisoM;
import model.SalaM;
import model.StatusM;
import model.SubTipoM;
import model.TipoM;
import model.UnidadeM;
import util.LimiteDigitos;

/**
 * UNIVERSIDADE DO ESTADO DE MINAS GERAIS - Unidade Frutal
 * @author NUPSI - Núcle de Práticas em Sistemas de Informação
 * Equipe: Gustavo Pinoti,Leopoldo Ferreira, Marlon Moro, Murillo Cuervo
 */
public class PatrimonioView extends javax.swing.JInternalFrame {

    /**
     * Creates new form Patrimonio
     */
    PisoM piso;
    PisoDAO pisoDAO;
    List<PisoM> listaPiso;
    List<BlocoM> listaBloco;
    BlocoDAO blocoDAO;
    List<UnidadeM> listaUnidade;
    UnidadeDAO unidadeDAO;
    SalaDAO salaDAO;
    List<SalaM> listaSala;
    List<GrauConservacaoM> listaGrau;
    List<StatusM> listaStatus;
    GrauConservacaoDAO grauDAO;
    StatusDAO statusDAO;
    List<OrgaoM> listaEntidade;
    OrgaoDAO entidadeDAO;
    List<TipoM> listaTipo;
    TipoDAO tipoDAO;
    List<SubTipoM> listaSub;
    SubTipoDAO subtipoDAO;
    List<PatrimonioM> listaPatrimonio;
    PatrimonioDAO patrimonioDAO;
    PatrimonioM patrimonio;
    
    PatrimonioM auxPatrimonio;
    PatrimonioCompostoM patComposto;
    PatrimonioCompostoDAO patrimonioCompostoDAO;
    List<PatrimonioCompostoM> listaComposto;
    
    BlocoM bloc;
    UnidadeM unid;
    PisoM pis;

    int ultimoID;
    
    public PatrimonioView() {
        pisoDAO = new PisoDAO();
        listaPiso = new ArrayList<>();
        listaBloco = new ArrayList<>();
        blocoDAO = new BlocoDAO();
        listaUnidade = new ArrayList<>();
        unidadeDAO = new UnidadeDAO();
        salaDAO = new SalaDAO();
        listaSala = new ArrayList<>();
        listaGrau = new ArrayList<>();
        listaStatus = new ArrayList<>();
        grauDAO = new GrauConservacaoDAO();
        statusDAO = new StatusDAO();
        listaEntidade = new ArrayList<>();
        entidadeDAO = new OrgaoDAO();
        listaTipo = new ArrayList<>();
        tipoDAO = new TipoDAO();
        listaSub = new ArrayList<>();
        subtipoDAO = new SubTipoDAO();
        listaPatrimonio = new ArrayList<>();
        patrimonioDAO = new PatrimonioDAO();
        
        listaComposto = new ArrayList<>();
        patrimonioCompostoDAO = new PatrimonioCompostoDAO();
        
        bloc = new BlocoM();
        unid = new UnidadeM();
        pis = new PisoM();
        
        initComponents();
        
        this.setVisible(true);
        pnlPatrimonioComposto.setVisible(false);
       
        atualizaBoxUnidade();
        atualizaBoxTipo();
        atualizaBoxGrauConservacao();
        atualizaBoxStatus();
        atualizaBoxEntidade();
        atualizaTabelaPatrimonio();
        tfdCodigoPatrimonio.setDocument(new LimiteDigitos(60));
        tfdDescricaoPatrimonio.setDocument(new LimiteDigitos(90));
        tfdNotaFiscalPatrimonio.setDocument(new LimiteDigitos(45));
        
        auxPatrimonio = new PatrimonioM();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPatrimonio = new javax.swing.JPanel();
        lblStatus = new javax.swing.JLabel();
        lblNotaFiscal = new javax.swing.JLabel();
        lblPatrimonio = new javax.swing.JLabel();
        tfdNotaFiscalPatrimonio = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfdCodigoPatrimonio = new javax.swing.JTextField();
        cbxOrgao = new javax.swing.JComboBox<>();
        lblDescricao = new javax.swing.JLabel();
        tfdDescricaoPatrimonio = new javax.swing.JTextField();
        lblGrauConservacao = new javax.swing.JLabel();
        cbxConservacao = new javax.swing.JComboBox<>();
        cbxStatus = new javax.swing.JComboBox<>();
        btnExcluirPatrimonio = new javax.swing.JButton();
        btnSalvarPatrimonio = new javax.swing.JButton();
        btnAlterarPatrimonio = new javax.swing.JButton();
        btnNovoPatrimonio = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        tfdIDPatrimonio = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblSelecUnidade = new javax.swing.JLabel();
        cbxUnidade = new javax.swing.JComboBox<>();
        lblSelecBloco = new javax.swing.JLabel();
        cbxBloco = new javax.swing.JComboBox<>();
        lblSelecPiso = new javax.swing.JLabel();
        cbxPiso = new javax.swing.JComboBox<>();
        lblSelecSala = new javax.swing.JLabel();
        cbxSala = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        lblSelecTipo = new javax.swing.JLabel();
        cbxTipo = new javax.swing.JComboBox<>();
        lblSelecSubtipo = new javax.swing.JLabel();
        cbxSuptipo = new javax.swing.JComboBox<>();
        btnCancelarPatrimonio = new javax.swing.JButton();
        pnlPatrimonioComposto = new javax.swing.JPanel();
        btnCancelarPatrimonioComposto = new javax.swing.JButton();
        btnExcluirPatrimonioComposto = new javax.swing.JButton();
        btnSalvarPatrimonioComposto = new javax.swing.JButton();
        btnAlterarPatrimonioComposto = new javax.swing.JButton();
        btnNovoPatrimonioComposto = new javax.swing.JButton();
        tfdDescricaoPatrimonioComposto = new javax.swing.JTextField();
        cbxStatusPatrimonioComposto = new javax.swing.JComboBox<>();
        lblGrauConservacao1 = new javax.swing.JLabel();
        lblDescricao1 = new javax.swing.JLabel();
        lblStatus1 = new javax.swing.JLabel();
        cbxConservacaoPatrimonioComposto = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbePatrimonioComposto = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfdIDComposto = new javax.swing.JTextField();
        btnCancelaComposto = new javax.swing.JButton();
        ckxPatrimonioComposto = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbePatrimonio = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastrar Patrimônio");

        lblStatus.setText("Status");

        lblNotaFiscal.setText("Nota Fiscal");

        lblPatrimonio.setText("Patrimônio");

        tfdNotaFiscalPatrimonio.setEnabled(false);

        lblCodigo.setText("Código");

        jLabel2.setText("Orgão");

        tfdCodigoPatrimonio.setEnabled(false);
        tfdCodigoPatrimonio.setPreferredSize(new java.awt.Dimension(6, 25));

        cbxOrgao.setEnabled(false);
        cbxOrgao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxOrgaoActionPerformed(evt);
            }
        });

        lblDescricao.setText("Descrição");

        tfdDescricaoPatrimonio.setEnabled(false);
        tfdDescricaoPatrimonio.setMinimumSize(new java.awt.Dimension(6, 25));
        tfdDescricaoPatrimonio.setPreferredSize(new java.awt.Dimension(6, 25));

        lblGrauConservacao.setText("Grau de Conservação");

        cbxConservacao.setEnabled(false);
        cbxConservacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxConservacaoActionPerformed(evt);
            }
        });

        cbxStatus.setEnabled(false);

        btnExcluirPatrimonio.setText("Excluir");
        btnExcluirPatrimonio.setEnabled(false);
        btnExcluirPatrimonio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirPatrimonioActionPerformed(evt);
            }
        });

        btnSalvarPatrimonio.setText("Salvar");
        btnSalvarPatrimonio.setEnabled(false);
        btnSalvarPatrimonio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarPatrimonioActionPerformed(evt);
            }
        });

        btnAlterarPatrimonio.setText("Alterar");
        btnAlterarPatrimonio.setEnabled(false);
        btnAlterarPatrimonio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarPatrimonioActionPerformed(evt);
            }
        });

        btnNovoPatrimonio.setText("Novo");
        btnNovoPatrimonio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoPatrimonioActionPerformed(evt);
            }
        });

        lblID.setText("ID");

        tfdIDPatrimonio.setEditable(false);
        tfdIDPatrimonio.setEnabled(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Localização"));

        lblSelecUnidade.setText("Selecione a unidade:");

        cbxUnidade.setEnabled(false);
        cbxUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxUnidadeActionPerformed(evt);
            }
        });

        lblSelecBloco.setText("Selecione o bloco:");

        cbxBloco.setEnabled(false);
        cbxBloco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxBlocoActionPerformed(evt);
            }
        });

        lblSelecPiso.setText("Selecione o piso:");

        cbxPiso.setEnabled(false);
        cbxPiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPisoActionPerformed(evt);
            }
        });

        lblSelecSala.setText("Selecione a sala:");

        cbxSala.setEnabled(false);
        cbxSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSalaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cbxUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblSelecUnidade)
            .addComponent(lblSelecBloco)
            .addComponent(cbxBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblSelecPiso)
            .addComponent(cbxPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblSelecSala)
            .addComponent(cbxSala, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblSelecUnidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSelecBloco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSelecPiso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSelecSala)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxSala, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Categoria"));

        lblSelecTipo.setText("Selecione o Tipo:");

        cbxTipo.setEnabled(false);
        cbxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoActionPerformed(evt);
            }
        });

        lblSelecSubtipo.setText("Selecione a Subtipo:");

        cbxSuptipo.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSelecTipo)
            .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblSelecSubtipo)
            .addComponent(cbxSuptipo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblSelecTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSelecSubtipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxSuptipo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnCancelarPatrimonio.setText("Cancelar");
        btnCancelarPatrimonio.setEnabled(false);
        btnCancelarPatrimonio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPatrimonioActionPerformed(evt);
            }
        });

        pnlPatrimonioComposto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Itens Cadastrados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        btnCancelarPatrimonioComposto.setText("Cancelar");
        btnCancelarPatrimonioComposto.setEnabled(false);
        btnCancelarPatrimonioComposto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPatrimonioCompostoActionPerformed(evt);
            }
        });

        btnExcluirPatrimonioComposto.setText("Excluir");
        btnExcluirPatrimonioComposto.setEnabled(false);
        btnExcluirPatrimonioComposto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirPatrimonioCompostoActionPerformed(evt);
            }
        });

        btnSalvarPatrimonioComposto.setText("Salvar");
        btnSalvarPatrimonioComposto.setEnabled(false);
        btnSalvarPatrimonioComposto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarPatrimonioCompostoActionPerformed(evt);
            }
        });

        btnAlterarPatrimonioComposto.setText("Alterar");
        btnAlterarPatrimonioComposto.setEnabled(false);
        btnAlterarPatrimonioComposto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarPatrimonioCompostoActionPerformed(evt);
            }
        });

        btnNovoPatrimonioComposto.setText("Novo");
        btnNovoPatrimonioComposto.setEnabled(false);
        btnNovoPatrimonioComposto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoPatrimonioCompostoActionPerformed(evt);
            }
        });

        tfdDescricaoPatrimonioComposto.setEnabled(false);
        tfdDescricaoPatrimonioComposto.setPreferredSize(new java.awt.Dimension(6, 25));

        cbxStatusPatrimonioComposto.setEnabled(false);

        lblGrauConservacao1.setText("Grau de Conservação");

        lblDescricao1.setText("Descrição");

        lblStatus1.setText("Status");

        cbxConservacaoPatrimonioComposto.setEnabled(false);
        cbxConservacaoPatrimonioComposto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxConservacaoPatrimonioCompostoActionPerformed(evt);
            }
        });

        tbePatrimonioComposto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Descrição", "Grau de Conservação", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbePatrimonioComposto.setEnabled(false);
        tbePatrimonioComposto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbePatrimonioCompostoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbePatrimonioComposto);

        jLabel3.setText("Patrimônio Composto");

        jLabel1.setText("ID:");

        tfdIDComposto.setEnabled(false);
        tfdIDComposto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdIDCompostoActionPerformed(evt);
            }
        });

        btnCancelaComposto.setText("Cancelar");
        btnCancelaComposto.setEnabled(false);
        btnCancelaComposto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaCompostoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPatrimonioCompostoLayout = new javax.swing.GroupLayout(pnlPatrimonioComposto);
        pnlPatrimonioComposto.setLayout(pnlPatrimonioCompostoLayout);
        pnlPatrimonioCompostoLayout.setHorizontalGroup(
            pnlPatrimonioCompostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPatrimonioCompostoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPatrimonioCompostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxStatusPatrimonioComposto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfdDescricaoPatrimonioComposto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxConservacaoPatrimonioComposto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlPatrimonioCompostoLayout.createSequentialGroup()
                        .addComponent(btnSalvarPatrimonioComposto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(btnCancelarPatrimonioComposto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(btnAlterarPatrimonioComposto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(btnExcluirPatrimonioComposto))
                    .addGroup(pnlPatrimonioCompostoLayout.createSequentialGroup()
                        .addGroup(pnlPatrimonioCompostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGrauConservacao1)
                            .addComponent(lblStatus1)
                            .addGroup(pnlPatrimonioCompostoLayout.createSequentialGroup()
                                .addGroup(pnlPatrimonioCompostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDescricao1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(tfdIDComposto, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlPatrimonioCompostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlPatrimonioCompostoLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel3))
                                    .addGroup(pnlPatrimonioCompostoLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnNovoPatrimonioComposto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnCancelaComposto)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlPatrimonioCompostoLayout.setVerticalGroup(
            pnlPatrimonioCompostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPatrimonioCompostoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPatrimonioCompostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pnlPatrimonioCompostoLayout.createSequentialGroup()
                        .addGroup(pnlPatrimonioCompostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(pnlPatrimonioCompostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfdIDComposto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelaComposto)
                            .addComponent(btnNovoPatrimonioComposto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDescricao1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdDescricaoPatrimonioComposto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGrauConservacao1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxConservacaoPatrimonioComposto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStatus1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxStatusPatrimonioComposto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPatrimonioCompostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnExcluirPatrimonioComposto)
                            .addComponent(btnSalvarPatrimonioComposto)
                            .addComponent(btnAlterarPatrimonioComposto)
                            .addComponent(btnCancelarPatrimonioComposto))))
                .addGap(0, 0, 0))
        );

        ckxPatrimonioComposto.setText("PatrimonioComposto");
        ckxPatrimonioComposto.setEnabled(false);
        ckxPatrimonioComposto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckxPatrimonioCompostoActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patrimônios Cadastrados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        tbePatrimonio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Código", "Descrição", "Grau de Consevação", "Status", "Nota Fiscal", "Orgão"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbePatrimonio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbePatrimonioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbePatrimonio);
        if (tbePatrimonio.getColumnModel().getColumnCount() > 0) {
            tbePatrimonio.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlPatrimonioLayout = new javax.swing.GroupLayout(pnlPatrimonio);
        pnlPatrimonio.setLayout(pnlPatrimonioLayout);
        pnlPatrimonioLayout.setHorizontalGroup(
            pnlPatrimonioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPatrimonioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPatrimonioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPatrimonioComposto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlPatrimonioLayout.createSequentialGroup()
                        .addGroup(pnlPatrimonioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlPatrimonioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPatrimonioLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(pnlPatrimonioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfdIDPatrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlPatrimonioLayout.createSequentialGroup()
                                        .addComponent(lblID)
                                        .addGap(57, 57, 57)
                                        .addComponent(lblPatrimonio))
                                    .addGroup(pnlPatrimonioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tfdCodigoPatrimonio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblGrauConservacao, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblStatus, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblNotaFiscal, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbxStatus, javax.swing.GroupLayout.Alignment.LEADING, 0, 270, Short.MAX_VALUE)
                                        .addComponent(cbxConservacao, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbxOrgao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfdDescricaoPatrimonio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfdNotaFiscalPatrimonio, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addGroup(pnlPatrimonioLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(pnlPatrimonioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ckxPatrimonioComposto)
                                    .addGroup(pnlPatrimonioLayout.createSequentialGroup()
                                        .addComponent(btnNovoPatrimonio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSalvarPatrimonio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCancelarPatrimonio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAlterarPatrimonio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnExcluirPatrimonio)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlPatrimonioLayout.setVerticalGroup(
            pnlPatrimonioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPatrimonioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPatrimonioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlPatrimonioLayout.createSequentialGroup()
                        .addGroup(pnlPatrimonioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPatrimonioLayout.createSequentialGroup()
                                .addGroup(pnlPatrimonioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlPatrimonioLayout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(lblID)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnlPatrimonioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfdIDPatrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(pnlPatrimonioLayout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(lblCodigo))))
                                    .addComponent(lblPatrimonio))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfdCodigoPatrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(lblDescricao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfdDescricaoPatrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(lblGrauConservacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxConservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblStatus)
                                .addGap(0, 0, 0)
                                .addComponent(cbxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNotaFiscal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfdNotaFiscalPatrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxOrgao, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ckxPatrimonioComposto)
                                .addGap(6, 6, 6)
                                .addGroup(pnlPatrimonioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnExcluirPatrimonio)
                                    .addComponent(btnNovoPatrimonio)
                                    .addComponent(btnSalvarPatrimonio)
                                    .addComponent(btnAlterarPatrimonio)
                                    .addComponent(btnCancelarPatrimonio)))
                            .addGroup(pnlPatrimonioLayout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlPatrimonioComposto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPatrimonio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPatrimonio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void iniciaComposto(){
        
        atualizaStatusComposto();
        atualizaGrauComposto();
        atualizaTabelaCompostoExistente();
        
    }
    
    
    public void atualizaTabelaPatrimonio() {

        try {
            listaPatrimonio = patrimonioDAO.listaTodos();
        } catch (SQLException ex) {
            Logger.getLogger(OrgaoView.class.getName()).log(Level.SEVERE, null, ex);
        }
        String dados[][] = new String[listaPatrimonio.size()][8];
        int i = 0;
        for (PatrimonioM pat : listaPatrimonio) {
            dados[i][0] = String.valueOf(pat.getId());
            dados[i][1] = pat.getCodigo();
            dados[i][2] = pat.getDescricao();
            dados[i][3] = pat.getSubTipo().getDescricao();
            dados[i][4] = pat.getSala().getDescricao();
            dados[i][5] = pat.getGrau_conservacao().getDescricao();
            dados[i][6] = pat.getStatus().getNome();
            dados[i][7] = pat.getEntidade().getNome();
            i++;
        }
        String tituloColuna[] = {"ID", "Codigo", "Descrição", "Subtipo", "Sala", "Grau de Conservação", "Status", "Entidade"};
        DefaultTableModel tabelaCliente = new DefaultTableModel();
        tabelaCliente.setDataVector(dados, tituloColuna);
        tbePatrimonio.setModel(new DefaultTableModel(dados, tituloColuna) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false, false, false, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

        tbePatrimonio.getColumnModel().getColumn(0).setPreferredWidth(80);
        tbePatrimonio.getColumnModel().getColumn(1).setPreferredWidth(100);
        tbePatrimonio.getColumnModel().getColumn(2).setPreferredWidth(150);
        tbePatrimonio.getColumnModel().getColumn(3).setPreferredWidth(150);
        tbePatrimonio.getColumnModel().getColumn(4).setPreferredWidth(100);
        tbePatrimonio.getColumnModel().getColumn(5).setPreferredWidth(100);
        tbePatrimonio.getColumnModel().getColumn(6).setPreferredWidth(100);
        tbePatrimonio.getColumnModel().getColumn(7).setPreferredWidth(100);

        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        tbePatrimonio.getColumnModel().getColumn(0).setCellRenderer(centralizado);
        tbePatrimonio.setRowHeight(25);
        tbePatrimonio.updateUI();
    }
    
    public void atualizaBoxTipo() {
        cbxTipo.removeAllItems();
        cbxTipo.addItem("--Selecione--");
        try {
            listaTipo = tipoDAO.listaTodos();
        } catch (SQLException ex) {
            Logger.getLogger(OrgaoView.class.getName()).log(Level.SEVERE, null, ex);
        }
        String dados[][] = new String[listaTipo.size()][5];
        int i = 0;
        for (TipoM tip : listaTipo) {
            cbxTipo.addItem(tip.getDescricao());
        }
    }

    public void atualizaBoxEntidade() {
        cbxOrgao.removeAllItems();
        cbxOrgao.addItem("--Selecione--");
        try {
            listaEntidade = entidadeDAO.listaTodos();
        } catch (SQLException ex) {
            Logger.getLogger(OrgaoView.class.getName()).log(Level.SEVERE, null, ex);
        }
        String dados[][] = new String[listaEntidade.size()][5];
        int i = 0;
        for (OrgaoM ent : listaEntidade) {
            cbxOrgao.addItem(ent.getNome());
        }
    }

    public void atualizaBoxGrauConservacao() {
        cbxConservacao.removeAllItems();
        cbxConservacao.addItem("--Selecione--");
        try {
            listaGrau = grauDAO.listaTodos();
        } catch (SQLException ex) {
            Logger.getLogger(OrgaoView.class.getName()).log(Level.SEVERE, null, ex);
        }
        String dados[][] = new String[listaGrau.size()][5];
        int i = 0;
        for (GrauConservacaoM gra : listaGrau) {
            cbxConservacao.addItem(gra.getDescricao());
        }
    }

    public void atualizaBoxStatus() {
        cbxStatus.removeAllItems();
        cbxStatus.addItem("--Selecione--");
        try {
            listaStatus = statusDAO.listaTodos();
        } catch (SQLException ex) {
            Logger.getLogger(OrgaoView.class.getName()).log(Level.SEVERE, null, ex);
        }
        String dados[][] = new String[listaStatus.size()][5];
        int i = 0;
        for (StatusM stat : listaStatus) {
            cbxStatus.addItem(stat.getNome());
        }
    }
     public void atualizaBoxUnidade() {
        cbxUnidade.removeAllItems();
        cbxUnidade.addItem("--Selecione--");
        try {
            listaUnidade = unidadeDAO.listaTodos();
        } catch (SQLException ex) {
            Logger.getLogger(OrgaoView.class.getName()).log(Level.SEVERE, null, ex);
        }
        String dados[][] = new String[listaUnidade.size()][5];
        int i = 0;
        for (UnidadeM uni : listaUnidade) {
            cbxUnidade.addItem(uni.getNome());
        }

    }

    private void cbxBlocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxBlocoActionPerformed
        if (cbxBloco.getSelectedIndex() < 1) {
            cbxPiso.removeAllItems();
            cbxPiso.addItem("--Selecione--");
        } else {
            cbxPiso.removeAllItems();
            cbxPiso.addItem("--Selecione--");
            

            try {
                //bloc = blocoDAO.buscaNome(cbxBloco.getSelectedItem().toString());
                bloc = blocoDAO.busca_id_unidade(unid.getId(), cbxBloco.getSelectedItem().toString());
                listaPiso = pisoDAO.buscaBloc(bloc.getId());
                for (PisoM pis : listaPiso) {
                    cbxPiso.addItem(pis.getDescricao());
                }
            } catch (SQLException ex) {
                cbxPiso.removeAllItems();
                cbxPiso.addItem("--Selecione--");
            }
        }
        
        
    }//GEN-LAST:event_cbxBlocoActionPerformed

   

    private void cbxSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSalaActionPerformed

    private void cbxUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxUnidadeActionPerformed

        if (cbxUnidade.getSelectedIndex() < 1) {
            cbxBloco.removeAllItems();
            cbxBloco.addItem("--Selecione--");

        } else {
            cbxBloco.removeAllItems();
            cbxBloco.addItem("--Selecione--");
            //UnidadeM unid = new UnidadeM();
            try {
                unid = unidadeDAO.buscaNome(cbxUnidade.getSelectedItem().toString());
                listaBloco = blocoDAO.buscaUni(unid.getId());
                for (BlocoM bloc : listaBloco) {
                    cbxBloco.addItem(bloc.getDescricao());
                }
            } catch (SQLException ex) {
                Logger.getLogger(PisoView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
    }//GEN-LAST:event_cbxUnidadeActionPerformed

    private void cbxPisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPisoActionPerformed
        if (cbxPiso.getSelectedIndex() < 1) {
            cbxSala.removeAllItems();
            cbxSala.addItem("--Selecione--");
        } else {
            cbxSala.removeAllItems();
            cbxSala.addItem("--Selecione--");
            //PisoM pis = new PisoM();

            try {
                //pis = pisoDAO.buscaNome(cbxPiso.getSelectedItem().toString());
                pis = pisoDAO.busca_id_bloco(bloc.getId(), cbxPiso.getSelectedItem().toString());
                listaSala = salaDAO.buscaPis(pis.getId());
                for (SalaM sal : listaSala) {
                    cbxSala.addItem(sal.getDescricao());
                }
            } catch (SQLException ex) {
                cbxPiso.removeAllItems();
                cbxPiso.addItem("--Selecione--");
            }
        }
    }//GEN-LAST:event_cbxPisoActionPerformed

    private void cbxConservacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxConservacaoActionPerformed

    }//GEN-LAST:event_cbxConservacaoActionPerformed

    private void cbxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoActionPerformed
        if (cbxTipo.getSelectedIndex() < 1) {
            cbxSuptipo.removeAllItems();
            cbxSuptipo.addItem("--Selecione--");
        } else {
            cbxSuptipo.removeAllItems();
            cbxSuptipo.addItem("--Selecione--");
            TipoM tip = new TipoM();
            try {
                tip = tipoDAO.buscaNome(cbxTipo.getSelectedItem().toString());
                listaSub = subtipoDAO.buscaTipo(tip.getId());
                for (SubTipoM subt : listaSub) {
                    cbxSuptipo.addItem(subt.getDescricao());
                }
            } catch (SQLException ex) {
                cbxSuptipo.removeAllItems();
                cbxSuptipo.addItem("--Selecione--");
            }
        }
    }//GEN-LAST:event_cbxTipoActionPerformed

    private void btnNovoPatrimonioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoPatrimonioActionPerformed
        limpaCamposPatrimonio();
        preparaNovo();
        ativaCamposNovo();
        tfdCodigoPatrimonio.requestFocusInWindow();  
    }//GEN-LAST:event_btnNovoPatrimonioActionPerformed

    private void tbePatrimonioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbePatrimonioMouseClicked
        
        
        tfdIDPatrimonio.setText(tbePatrimonio.getValueAt(tbePatrimonio.getSelectedRow(), 0).toString());
        tfdCodigoPatrimonio.setText(tbePatrimonio.getValueAt(tbePatrimonio.getSelectedRow(), 1).toString());
        tfdDescricaoPatrimonio.setText(tbePatrimonio.getValueAt(tbePatrimonio.getSelectedRow(), 2).toString());
        PatrimonioM patri = pegaPatrimonio();
        
        cbxTipo.setSelectedItem(patri.getSubTipo().getTipo().getDescricao());
        cbxSuptipo.setSelectedItem(tbePatrimonio.getValueAt(tbePatrimonio.getSelectedRow(), 3).toString());
       
        cbxUnidade.setSelectedItem(patri.getSala().getPiso().getBloco().getUnidadeM().getNome());
        cbxBloco.setSelectedItem(patri.getSala().getPiso().getBloco().getDescricao());
        cbxPiso.setSelectedItem(patri.getSala().getPiso().getDescricao());
        cbxSala.setSelectedItem(patri.getSala().getDescricao());
        cbxConservacao.setSelectedItem(tbePatrimonio.getValueAt(tbePatrimonio.getSelectedRow(), 5).toString());
        cbxStatus.setSelectedItem(tbePatrimonio.getValueAt(tbePatrimonio.getSelectedRow(), 6).toString());
        cbxOrgao.setSelectedItem(tbePatrimonio.getValueAt(tbePatrimonio.getSelectedRow(), 7).toString());
        tfdNotaFiscalPatrimonio.setText(patri.getNotaFiscal());
        ckxPatrimonioComposto.setSelected(patri.getKit());
        
        auxPatrimonio = patri;
        
        
        if(patri.getKit())
            
        {
            iniciaComposto();
            pnlPatrimonioComposto.setVisible(true);
        }else
        {
            pnlPatrimonioComposto.setVisible(false);
        }
        
        preparaSelecaoTabelaPatrimonio();
    }//GEN-LAST:event_tbePatrimonioMouseClicked

    
    public PatrimonioM pegaPatrimonio(){
        try {
            PatrimonioM patrimo = patrimonioDAO.busca(Integer.parseInt(tbePatrimonio.getValueAt(tbePatrimonio.getSelectedRow(), 0).toString()));
            return patrimo;
        } catch (SQLException ex) {
            Logger.getLogger(PatrimonioView.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    private void btnSalvarPatrimonioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarPatrimonioActionPerformed
     
        if (tfdDescricaoPatrimonio.getText().isEmpty() || tfdCodigoPatrimonio.getText().isEmpty() || tfdNotaFiscalPatrimonio.getText().isEmpty() || cbxSala.getSelectedIndex() == 0 || cbxConservacao.getSelectedIndex() == 0 || cbxOrgao.getSelectedIndex() == 0 || cbxStatus.getSelectedIndex() == 0 || cbxSuptipo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Prencha todos os campos.", "Erro", JOptionPane.WARNING_MESSAGE);
            tfdDescricaoPatrimonio.requestFocusInWindow();
        } else  if (tfdIDPatrimonio.getText().isEmpty()){
            //Se estiver o campo ID estiver vazio siginifica que será um novo objeto.
            patrimonio = new PatrimonioM();
            patrimonio.setDescricao(tfdDescricaoPatrimonio.getText());
            patrimonio.setCodigo(tfdCodigoPatrimonio.getText());
            patrimonio.setEntidade(pegaEntidade());
            patrimonio.setGrau_conservacao(pegaGrau(cbxConservacao.getSelectedItem().toString()));
            patrimonio.setNotaFiscal(tfdNotaFiscalPatrimonio.getText());
            patrimonio.setSala(pegaSala());
            patrimonio.setStatus(pegaStatus(cbxStatus.getSelectedItem().toString()));
            patrimonio.setSubTipo(pegaSubtipo());
            patrimonio.setKit(ckxPatrimonioComposto.isSelected());
            try {
                //Recebe o ultimo ID gerado
                ultimoID = patrimonioDAO.salvar(patrimonio);
                auxPatrimonio = patrimonioDAO.busca(ultimoID);
                // a partir daqui tem que liberar a tela do composto
                if (ckxPatrimonioComposto.isSelected())
                {
                    desativaCampos();
                    pnlPatrimonioComposto.setVisible(true);
                    iniciaComposto();
                    JOptionPane.showMessageDialog(null, "Cadastre os itens do kit", "Cadastro de Kit", JOptionPane.INFORMATION_MESSAGE);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Patrimônio cadastrado com sucesso..", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                    preparaSalvareCancelar();
                    limpaCamposPatrimonio();
                }         
                atualizaTabelaPatrimonio();
                
            } catch (SQLException ex) {
                Logger.getLogger(OrgaoView.class.getName()).log(Level.SEVERE, null, ex);
                if (ex.getErrorCode() == 1062) {
                    JOptionPane.showMessageDialog(null, "Patrimônio já existente.", "Erro", JOptionPane.WARNING_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.WARNING_MESSAGE);
                }
            }
        } else {
            int auxID = Integer.parseInt(tfdIDPatrimonio.getText());
            //Se for uma situação de alteração ele vai pegar o ID do patrimonio direto do textfield
            try {
                //cria o auxiliar a partir do ID
                auxPatrimonio = patrimonioDAO.busca(auxID);
            } catch (SQLException ex) {
                Logger.getLogger(PatrimonioView.class.getName()).log(Level.SEVERE, null, ex);
            }
            //Se o campo ID não estiver vazio trata-se de uma alteração
            patrimonio = new PatrimonioM();
            patrimonio.setId(Integer.parseInt(tfdIDPatrimonio.getText()));
            patrimonio.setDescricao(tfdDescricaoPatrimonio.getText());
            patrimonio.setCodigo(tfdCodigoPatrimonio.getText());
            patrimonio.setNotaFiscal(tfdNotaFiscalPatrimonio.getText());
            patrimonio.setKit(ckxPatrimonioComposto.isSelected());
            
            try{
                patrimonioDAO.alterar(patrimonio);
                
                if (ckxPatrimonioComposto.isSelected()){
                    pnlPatrimonioComposto.setVisible(true);
                    iniciaComposto();
                    desativaCampos();
                    JOptionPane.showMessageDialog(null, "Cadastre os itens do kit", "Cadastro de Kit", JOptionPane.INFORMATION_MESSAGE);
                    ativaComposto();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Patrimônio atualizado com sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                    preparaSalvareCancelar();
                    limpaCamposPatrimonio();
                }
                atualizaTabelaPatrimonio();    
            }catch (SQLException ex) {
                Logger.getLogger(OrgaoView.class.getName()).log(Level.SEVERE, null, ex);
                 if (ex.getErrorCode() == 1062) {
                    JOptionPane.showMessageDialog(null, "Patrimônio já existente.", "Erro", JOptionPane.WARNING_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.WARNING_MESSAGE);
                }
            } 
        }    
    }//GEN-LAST:event_btnSalvarPatrimonioActionPerformed

    private void btnExcluirPatrimonioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirPatrimonioActionPerformed
        if (tfdIDPatrimonio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione um Patrimônio.", "Erro", JOptionPane.WARNING_MESSAGE);
        } else {
            patrimonio = new PatrimonioM();
            patrimonio.setId(Integer.parseInt(tfdIDPatrimonio.getText()));
            int confirma = JOptionPane.showConfirmDialog(null, "Deseja Excluir: " + tfdDescricaoPatrimonio.getText() + " ?");
            if (confirma == 0) {
                try {
                    patrimonioDAO.excluir(patrimonio);
                    limpaCamposPatrimonio();
                    atualizaTabelaPatrimonio();
                    preparaExcluir();
                    desativaCampos();
                    JOptionPane.showMessageDialog(null, "Patrimônio excluído com sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                    
                } catch (SQLException ex) {
                    Logger.getLogger(OrgaoView.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        
        }
        
    }//GEN-LAST:event_btnExcluirPatrimonioActionPerformed

    private void btnAlterarPatrimonioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarPatrimonioActionPerformed
        preparaAlterar();
        ativaCamposAlterar();
    }//GEN-LAST:event_btnAlterarPatrimonioActionPerformed

    private void btnCancelarPatrimonioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPatrimonioActionPerformed
        limpaCamposPatrimonio();
        preparaSalvareCancelar();
        desativaCampos();       
    }//GEN-LAST:event_btnCancelarPatrimonioActionPerformed

    private void cbxOrgaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxOrgaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxOrgaoActionPerformed

    private void btnCancelarPatrimonioCompostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPatrimonioCompostoActionPerformed
        // TODO add your handling code here:
        limpaCamposComposto();
        preparaSalvarCancelarComposto();
        desativaCamposComposto();
    }//GEN-LAST:event_btnCancelarPatrimonioCompostoActionPerformed

    private void btnExcluirPatrimonioCompostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirPatrimonioCompostoActionPerformed
        // TODO add your handling code here:
        if (tfdIDComposto.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Selecione um Item.", "Erro", JOptionPane.WARNING_MESSAGE);
        } else {
            patComposto = new PatrimonioCompostoM();
            patComposto.setId(Integer.parseInt(tfdIDComposto.getText()));
            int confirma = JOptionPane.showConfirmDialog(null, "Deseja Excluir: " + tfdDescricaoPatrimonioComposto.getText() + " ?");
            if (confirma == 0) {
                try {
                    patrimonioCompostoDAO.excluir(patComposto);
                    atualizaTabelaCompostoExistente();
                    limpaCamposComposto();
                    preparaExcluir();
                } catch (SQLException ex) {
                    Logger.getLogger(PatrimonioView.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.WARNING_MESSAGE);
                }

            }
        }
        
        
    }//GEN-LAST:event_btnExcluirPatrimonioCompostoActionPerformed

    private void btnSalvarPatrimonioCompostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarPatrimonioCompostoActionPerformed
        // TODO add your handling code here:
        String status, conservacao;
        if (tfdDescricaoPatrimonioComposto.getText().isEmpty() || cbxConservacaoPatrimonioComposto.getSelectedIndex() == 0 || cbxStatusPatrimonioComposto.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Prencha todos os campos.", "Erro", JOptionPane.WARNING_MESSAGE);
            tfdDescricaoPatrimonioComposto.requestFocusInWindow();
        } else if (tfdIDComposto.getText().isEmpty()){           
            status = cbxStatusPatrimonioComposto.getSelectedItem().toString();
            conservacao = cbxConservacaoPatrimonioComposto.getSelectedItem().toString();
            patComposto = new PatrimonioCompostoM();
            patComposto.setDescricao(tfdDescricaoPatrimonioComposto.getText());
            patComposto.setGrau(pegaGrau(conservacao));  
            patComposto.setStatus(pegaStatus(status));
            patComposto.setPatrimonio(auxPatrimonio);
            try {
                patrimonioCompostoDAO.salvar(patComposto);
                JOptionPane.showMessageDialog(null, "Gravado com Sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex){
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            preparaSalvarCancelarComposto();
            desativaCamposComposto();
            atualizaTabelaCompostoExistente();
            limpaCamposComposto();
                        
        } else {
            status = cbxStatusPatrimonioComposto.getSelectedItem().toString();
            conservacao = cbxConservacaoPatrimonioComposto.getSelectedItem().toString();
            
            patComposto = new PatrimonioCompostoM();
            patComposto.setId(Integer.parseInt(tfdIDComposto.getText()));
            patComposto.setDescricao(tfdDescricaoPatrimonioComposto.getText());
            patComposto.setGrau(pegaGrau(conservacao));  
            patComposto.setStatus(pegaStatus(status));
            patComposto.setPatrimonio(auxPatrimonio);
            try{
                patrimonioCompostoDAO.alterar(patComposto);
                JOptionPane.showMessageDialog(null, "Alterado com Sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                Logger.getLogger(PatrimonioView.class.getName()).log(Level.SEVERE, null, ex);
            } 
            preparaSalvarCancelarComposto();
            desativaCamposComposto();
            atualizaTabelaCompostoExistente();
            limpaCamposComposto();
        }
    }//GEN-LAST:event_btnSalvarPatrimonioCompostoActionPerformed

    private void btnAlterarPatrimonioCompostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarPatrimonioCompostoActionPerformed
        // TODO add your handling code here:
        preparaAlterarComposto();
        ativaCamposComposto();
    }//GEN-LAST:event_btnAlterarPatrimonioCompostoActionPerformed

    private void btnNovoPatrimonioCompostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoPatrimonioCompostoActionPerformed
        // TODO add your handling code here:
        limpaCamposComposto();
        ativaCamposComposto();
        preparaNovoComposto();
        tfdDescricaoPatrimonioComposto.requestFocusInWindow();
        
    }//GEN-LAST:event_btnNovoPatrimonioCompostoActionPerformed

    private void cbxConservacaoPatrimonioCompostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxConservacaoPatrimonioCompostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxConservacaoPatrimonioCompostoActionPerformed

    private void ckxPatrimonioCompostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckxPatrimonioCompostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckxPatrimonioCompostoActionPerformed

    private void tfdIDCompostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdIDCompostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdIDCompostoActionPerformed

    private void tbePatrimonioCompostoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbePatrimonioCompostoMouseClicked
        // TODO add your handling code here:    
        PatrimonioCompostoM auxIDComposto = new PatrimonioCompostoM();
        try {
            auxIDComposto = patrimonioCompostoDAO.buscaDescricao(tbePatrimonioComposto.getValueAt(tbePatrimonioComposto.getSelectedRow(), 0).toString());
        } catch (SQLException ex) {
            Logger.getLogger(PatrimonioView.class.getName()).log(Level.SEVERE, null, ex);
        }
        int id = auxIDComposto.getId();
        tfdIDComposto.setText(String.valueOf(id));
        tfdDescricaoPatrimonioComposto.setText(tbePatrimonioComposto.getValueAt(tbePatrimonioComposto.getSelectedRow(), 0).toString());
        cbxConservacaoPatrimonioComposto.setSelectedItem(tbePatrimonioComposto.getValueAt(tbePatrimonioComposto.getSelectedRow(), 1).toString());
        cbxStatusPatrimonioComposto.setSelectedItem(tbePatrimonioComposto.getValueAt(tbePatrimonioComposto.getSelectedRow(), 2).toString());
        preparaSelecaoComposto();
    }//GEN-LAST:event_tbePatrimonioCompostoMouseClicked

    private void btnCancelaCompostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaCompostoActionPerformed
        // TODO add your handling code here:
        pnlPatrimonioComposto.setVisible(false);
        preparaSalvareCancelar();
        limpaCamposPatrimonio();
        
    }//GEN-LAST:event_btnCancelaCompostoActionPerformed

    public OrgaoM pegaEntidade() {
        try {
            return entidadeDAO.buscaNome(cbxOrgao.getSelectedItem().toString());
        } catch (SQLException ex) {
            Logger.getLogger(BlocoView.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    

    public GrauConservacaoM pegaGrau(String grau) {
        try {
            return grauDAO.buscaNome(grau);
        } catch (SQLException ex) {
            Logger.getLogger(BlocoView.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    public SalaM pegaSala() {
        try {
            return salaDAO.buscaNome(cbxSala.getSelectedItem().toString());
        } catch (SQLException ex) {
            Logger.getLogger(BlocoView.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public SubTipoM pegaSubtipo() {
        try {
            return subtipoDAO.buscaNome(cbxSuptipo.getSelectedItem().toString());
        } catch (SQLException ex) {
            Logger.getLogger(BlocoView.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public int pegaIDStatus(String status) {
        try {
            StatusM aux = new StatusM();
            aux = statusDAO.buscaNome(status);
            
            return aux.getId();
        } catch (SQLException ex) {
            Logger.getLogger(BlocoView.class.getName()).log(Level.SEVERE, null, ex);
        }
        return 1;
    }
    
    public StatusM pegaStatus(String status) {
        try {
            return statusDAO.buscaNome(status);
        } catch (SQLException ex) {
            Logger.getLogger(BlocoView.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    // INÍCIO MÉTODOS DE CONTROLE DE BOTÕES 
    
    public void limpaCamposPatrimonio() {
        
        cbxUnidade.setSelectedIndex(0);
        cbxTipo.setSelectedIndex(0);
        cbxConservacao.setSelectedIndex(0);
        cbxStatus.setSelectedIndex(0);
        cbxOrgao.setSelectedIndex(0);
        tfdIDPatrimonio.setText("");
        tfdCodigoPatrimonio.setText("");
        tfdDescricaoPatrimonio.setText("");
        tfdNotaFiscalPatrimonio.setText("");
        btnNovoPatrimonio.setEnabled(true);
        ckxPatrimonioComposto.setSelected(false);
        
        
    }
    
    public void preparaNovo() {
        btnNovoPatrimonio.setEnabled(false);
        btnCancelarPatrimonio.setEnabled(true);
        btnSalvarPatrimonio.setEnabled(true);
        btnAlterarPatrimonio.setEnabled(false);
        btnExcluirPatrimonio.setEnabled(false);
        tbePatrimonio.setEnabled(false);
        tbePatrimonio.clearSelection();
        
    }
    
    public void preparaSalvareCancelar() {
        btnNovoPatrimonio.setEnabled(true);
        btnCancelarPatrimonio.setEnabled(false);
        btnSalvarPatrimonio.setEnabled(false);
        tbePatrimonio.setEnabled(true);
    }
    
    public void ativaCamposNovo() {
        tfdCodigoPatrimonio.setEnabled(true);
        tfdDescricaoPatrimonio.setEnabled(true);
        tfdNotaFiscalPatrimonio.setEnabled(true);
       
        cbxConservacao.setEnabled(true);     
        cbxStatus.setEnabled(true);
        cbxConservacao.setEnabled(true);
        cbxOrgao.setEnabled(true);
   
        cbxUnidade.setEnabled(true);
        cbxBloco.setEnabled(true);
        cbxPiso.setEnabled(true);
        cbxSala.setEnabled(true);
        cbxTipo.setEnabled(true);
        cbxSuptipo.setEnabled(true);
        ckxPatrimonioComposto.setEnabled(true);
     
        
    }
    
    public void ativaCamposAlterar(){
        tfdCodigoPatrimonio.setEnabled(true);
        tfdDescricaoPatrimonio.setEnabled(true);
        tfdNotaFiscalPatrimonio.setEnabled(true);
       
        cbxConservacao.setEnabled(true);     
        cbxStatus.setEnabled(true);
        cbxStatus.setEnabled(true);
        cbxConservacao.setEnabled(true);
        cbxOrgao.setEnabled(true);
        //ckxPatrimonioComposto.setEnabled(true);
        
    }
    
    public void desativaCampos(){
              
        cbxConservacao.setSelectedIndex(0);
        cbxConservacao.setEnabled(false);
        cbxStatus.setSelectedIndex(0);
        cbxStatus.setEnabled(false);
        cbxOrgao.setSelectedIndex(0);
        cbxOrgao.setEnabled(false);
        cbxUnidade.setEnabled(false);
        cbxUnidade.setSelectedIndex(0);
        cbxBloco.setEnabled(false);
        cbxBloco.setSelectedIndex(0);
        cbxPiso.setEnabled(false);
        cbxPiso.setSelectedIndex(0);
        cbxSala.setEnabled(false);
        cbxSala.setSelectedIndex(0);
        cbxTipo.setEnabled(false);
        cbxTipo.setSelectedIndex(0);
        cbxSuptipo.setEnabled(false);
        cbxSuptipo.setSelectedIndex(0);
       
        //tfdIDPatrimonio.setText("");
        tfdIDPatrimonio.setEnabled(false);
        //tfdCodigoPatrimonio.setText("");
        tfdCodigoPatrimonio.setEnabled(false);
        //tfdDescricaoPatrimonio.setText("");
        tfdDescricaoPatrimonio.setEnabled(false);
        //tfdNotaFiscalPatrimonio.setText("");
        tfdNotaFiscalPatrimonio.setEnabled(false);
        
        ckxPatrimonioComposto.setEnabled(false);
 
        btnCancelarPatrimonio.setEnabled(false);
        btnSalvarPatrimonio.setEnabled(false);
        btnAlterarPatrimonio.setEnabled(false);
        btnExcluirPatrimonio.setEnabled(false);
    } 
    
    public void preparaAlterar() {
        btnNovoPatrimonio.setEnabled(false);
        btnExcluirPatrimonio.setEnabled(false);
        btnAlterarPatrimonio.setEnabled(false);
        btnCancelarPatrimonio.setEnabled(true);
        btnSalvarPatrimonio.setEnabled(true);
        
        cbxConservacao.setEnabled(false);
        cbxStatus.setEnabled(false);
        cbxOrgao.setEnabled(false);
        tbePatrimonio.setEnabled(false);        
        tbePatrimonio.clearSelection();
        tfdDescricaoPatrimonio.requestFocusInWindow();
    
    }
    
    public void preparaExcluir() {
        btnExcluirPatrimonio.setEnabled(false);
        btnAlterarPatrimonio.setEnabled(false);
        
    }
     
    public void preparaSelecaoTabelaPatrimonio(){
       
        btnNovoPatrimonio.setEnabled(true);
        btnExcluirPatrimonio.setEnabled(true);
        btnAlterarPatrimonio.setEnabled(true);       
 
    }
         
    // FIM MÉTODOS DE CONTROLE DE BOTÕES 
    
    
    
    // INICIO CONTROLE BOOTES COMPOSTO
    public void limpaCamposComposto(){
        tfdDescricaoPatrimonioComposto.setText("");
        cbxConservacaoPatrimonioComposto.setSelectedIndex(0);
        cbxStatusPatrimonioComposto.setSelectedIndex(0);                
    }
    
    public void ativaCamposComposto(){
        tfdDescricaoPatrimonioComposto.setEnabled(true);
        cbxConservacaoPatrimonioComposto.setEnabled(true);
        cbxStatusPatrimonioComposto.setEnabled(true);   
    }
    
    public void preparaNovoComposto(){
        btnNovoPatrimonioComposto.setEnabled(false);
        btnSalvarPatrimonioComposto.setEnabled(true);
        btnCancelarPatrimonioComposto.setEnabled(true);
        btnAlterarPatrimonioComposto.setEnabled(false);
        btnExcluirPatrimonioComposto.setEnabled(false);
        btnCancelaComposto.setEnabled(true);
        
        //tfdDescricaoPatrimonioComposto.setEnabled(true);
        cbxConservacaoPatrimonioComposto.setEnabled(true);
        cbxStatusPatrimonioComposto.setEnabled(true);
        tbePatrimonioComposto.setEnabled(false);
        tbePatrimonioComposto.clearSelection();
    }
    
    public void preparaSalvarCancelarComposto(){
        btnNovoPatrimonioComposto.setEnabled(true);
        btnSalvarPatrimonioComposto.setEnabled(false);
        btnCancelarPatrimonioComposto.setEnabled(false);
        btnCancelaComposto.setEnabled(true);
        
        cbxConservacaoPatrimonioComposto.setEnabled(false);
        cbxStatusPatrimonioComposto.setEnabled(false);
        tbePatrimonioComposto.setEnabled(true);
    }
    
    public void desativaCamposComposto(){
       tfdIDComposto.setText("");
       tfdIDComposto.setEnabled(false);
       tfdDescricaoPatrimonioComposto.setEnabled(false);
       cbxConservacaoPatrimonioComposto.setSelectedIndex(0);
       cbxConservacaoPatrimonioComposto.setEnabled(false);
       cbxStatusPatrimonioComposto.setSelectedIndex(0);
       cbxStatusPatrimonioComposto.setEnabled(false);
      
       btnSalvarPatrimonioComposto.setEnabled(false);
       btnCancelarPatrimonioComposto.setEnabled(false);
       btnAlterarPatrimonioComposto.setEnabled(false);
       btnExcluirPatrimonioComposto.setEnabled(false);
    }
    
    public void preparaAlterarComposto(){
        btnNovoPatrimonioComposto.setEnabled(false);
        btnExcluirPatrimonioComposto.setEnabled(false);
        btnAlterarPatrimonioComposto.setEnabled(false);
        btnSalvarPatrimonioComposto.setEnabled(true);
        btnCancelarPatrimonioComposto.setEnabled(true);
        tbePatrimonioComposto.setEnabled(false);
        tbePatrimonioComposto.clearSelection();
    }
    
    public void preparaSelecaoComposto(){
        btnNovoPatrimonioComposto.setEnabled(true);
        btnExcluirPatrimonioComposto.setEnabled(true);
        btnAlterarPatrimonioComposto.setEnabled(true);
    }
    
    public void ativaComposto(){
        tbePatrimonioComposto.setEnabled(true);
        btnNovoPatrimonioComposto.setEnabled(true);
        btnCancelaComposto.setEnabled(true);
    }
    
    public PatrimonioCompostoM pegaComposto(String descricao){
        try {
            return patrimonioCompostoDAO.buscaDescricao(descricao);
        } catch (SQLException ex) {
            Logger.getLogger(BlocoView.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    
    public void atualizaGrauComposto(){
        cbxConservacaoPatrimonioComposto.removeAllItems();
        cbxConservacaoPatrimonioComposto.addItem("--Selecione--");
        try {
            listaGrau = grauDAO.listaTodos();
        } catch (SQLException ex) {
            Logger.getLogger(OrgaoView.class.getName()).log(Level.SEVERE, null, ex);
        }
        String dados[][] = new String[listaGrau.size()][5];
        int i = 0;
        for (GrauConservacaoM gra : listaGrau) {
            cbxConservacaoPatrimonioComposto.addItem(gra.getDescricao());
        }
    }
    
    public void atualizaStatusComposto(){
        cbxStatusPatrimonioComposto.removeAllItems();
        cbxStatusPatrimonioComposto.addItem("--Selecione--");
        try {
            listaStatus = statusDAO.listaTodos();
        } catch (SQLException ex) {
            Logger.getLogger(OrgaoView.class.getName()).log(Level.SEVERE, null, ex);
        }
        String dados[][] = new String[listaStatus.size()][5];
        int i = 0;
        for (StatusM stat : listaStatus) {
            cbxStatusPatrimonioComposto.addItem(stat.getNome());
        }
        
    }
        
    public void atualizaTabelaCompostoExistente(){
        try {
            //compoe a lista de patrimonio composto a partir do ID do patrimonio que está sendo salvo.
            listaComposto = patrimonioCompostoDAO.listaTodosExistentes(auxPatrimonio);
        } catch (SQLException ex) {
            Logger.getLogger(PatrimonioView.class.getName()).log(Level.SEVERE, null, ex);
        }
        String dados[][] = new String[listaComposto.size()][4];
        int i = 0;
        for (PatrimonioCompostoM patComposto : listaComposto){
            dados[i][0] = patComposto.getDescricao();
            dados[i][1] = patComposto.getGrau().getDescricao();
            dados[i][2] = patComposto.getPatrimonio().getStatus().getNome();
            i++;
        }
        String tituloColuna[] = {"Descrição", "Grau de Conservação", "Status"};
        DefaultTableModel tabelaComposto = new DefaultTableModel();
        tabelaComposto.setDataVector(dados, tituloColuna);
        tbePatrimonioComposto.setModel(new DefaultTableModel(dados, tituloColuna){
            boolean[] canEdit = new boolean[]{ false, false, false 
            };
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex){
                return canEdit[columnIndex];
            }
        });
        
        tbePatrimonioComposto.getColumnModel().getColumn(0).setPreferredWidth(50);
        tbePatrimonioComposto.getColumnModel().getColumn(1).setPreferredWidth(300);
        tbePatrimonioComposto.getColumnModel().getColumn(2).setPreferredWidth(300);
        //tbePatrimonioComposto.getColumnModel().getColumn(3).setPreferredWidth(300);
        
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        tbePatrimonioComposto.getColumnModel().getColumn(0).setCellRenderer(centralizado);
        tbePatrimonioComposto.setRowHeight(25);
        tbePatrimonioComposto.updateUI();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarPatrimonio;
    private javax.swing.JButton btnAlterarPatrimonioComposto;
    private javax.swing.JButton btnCancelaComposto;
    private javax.swing.JButton btnCancelarPatrimonio;
    private javax.swing.JButton btnCancelarPatrimonioComposto;
    private javax.swing.JButton btnExcluirPatrimonio;
    private javax.swing.JButton btnExcluirPatrimonioComposto;
    private javax.swing.JButton btnNovoPatrimonio;
    private javax.swing.JButton btnNovoPatrimonioComposto;
    private javax.swing.JButton btnSalvarPatrimonio;
    private javax.swing.JButton btnSalvarPatrimonioComposto;
    private javax.swing.JComboBox<String> cbxBloco;
    private javax.swing.JComboBox<String> cbxConservacao;
    private javax.swing.JComboBox<String> cbxConservacaoPatrimonioComposto;
    private javax.swing.JComboBox<String> cbxOrgao;
    private javax.swing.JComboBox<String> cbxPiso;
    private javax.swing.JComboBox<String> cbxSala;
    private javax.swing.JComboBox<String> cbxStatus;
    private javax.swing.JComboBox<String> cbxStatusPatrimonioComposto;
    private javax.swing.JComboBox<String> cbxSuptipo;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JComboBox<String> cbxUnidade;
    private javax.swing.JCheckBox ckxPatrimonioComposto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblDescricao1;
    private javax.swing.JLabel lblGrauConservacao;
    private javax.swing.JLabel lblGrauConservacao1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNotaFiscal;
    private javax.swing.JLabel lblPatrimonio;
    private javax.swing.JLabel lblSelecBloco;
    private javax.swing.JLabel lblSelecPiso;
    private javax.swing.JLabel lblSelecSala;
    private javax.swing.JLabel lblSelecSubtipo;
    private javax.swing.JLabel lblSelecTipo;
    private javax.swing.JLabel lblSelecUnidade;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStatus1;
    private javax.swing.JPanel pnlPatrimonio;
    private javax.swing.JPanel pnlPatrimonioComposto;
    private javax.swing.JTable tbePatrimonio;
    private javax.swing.JTable tbePatrimonioComposto;
    private javax.swing.JTextField tfdCodigoPatrimonio;
    private javax.swing.JTextField tfdDescricaoPatrimonio;
    private javax.swing.JTextField tfdDescricaoPatrimonioComposto;
    private javax.swing.JTextField tfdIDComposto;
    private javax.swing.JTextField tfdIDPatrimonio;
    private javax.swing.JTextField tfdNotaFiscalPatrimonio;
    // End of variables declaration//GEN-END:variables
}
