package view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Frame;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import model.UsuarioM;

/**
 * UNIVERSIDADE DO ESTADO DE MINAS GERAIS - Unidade Frutal
 * @author NUPSI - Núcle de Práticas em Sistemas de Informação
 */
public class PrincipalView extends javax.swing.JFrame {

    public static UsuarioM usuarioAtivo = new UsuarioM();
    public PrincipalView(UsuarioM usuario) {
        initComponents();
        this.setVisible(true);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        usuarioAtivo = usuario;
        if(usuario.isAdmin() == false){
             mnuCadastrar.setEnabled(false);
             mniAdicionarUsuario.setEnabled(false);
        }
        URL url = this.getClass().getResource("/view/icones/icon.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
      //  mniMinhaConta.setEnabled(false);
        
        
    }

    PrincipalView() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        ImageIcon icon = new ImageIcon(getClass().getResource("/view/icones/uemg.png"));

        Image image = icon.getImage();
        pnlPrincipal = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image,pnlPrincipal.getWidth()/2 - icon.getIconWidth()/2,pnlPrincipal.getHeight()/2 - icon.getIconHeight()/2,this);
            }
        };
        mnbPrincipal = new javax.swing.JMenuBar();
        mnuCadastrar = new javax.swing.JMenu();
        mniOrgao = new javax.swing.JMenuItem();
        mnuLocalizacao = new javax.swing.JMenu();
        mniUnidade = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mniBloco = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mniPiso = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mniSala = new javax.swing.JMenuItem();
        mnuPatrimonio = new javax.swing.JMenu();
        mniIncluirPatrimonio = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniTipoSubtipo = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniConservacaoStatus = new javax.swing.JMenuItem();
        mnuMovimentacoes = new javax.swing.JMenu();
        mnuConsulta = new javax.swing.JMenu();
        mniConsultaPatrimonio = new javax.swing.JMenuItem();
        mniConsultaHistórico = new javax.swing.JMenuItem();
        mniConsultaBaixados = new javax.swing.JMenuItem();
        mnuRelatorios = new javax.swing.JMenu();
        mniRelatorioSala = new javax.swing.JMenuItem();
        mniRelatorioDescricao = new javax.swing.JMenuItem();
        mniRelatorioOrgao = new javax.swing.JMenuItem();
        mnuInventario = new javax.swing.JMenu();
        mnuUsuario = new javax.swing.JMenu();
        mniMinhaConta = new javax.swing.JMenuItem();
        mniAdicionarUsuario = new javax.swing.JMenuItem();
        mnuSobre = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Patrimônio - UEMG");

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1117, Short.MAX_VALUE)
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 941, Short.MAX_VALUE)
        );

        mnbPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        mnuCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/Crystal_Clear_action_edit_add.png"))); // NOI18N
        mnuCadastrar.setText("Arquivo");

        mniOrgao.setText("Orgão");
        mniOrgao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniOrgaoActionPerformed(evt);
            }
        });
        mnuCadastrar.add(mniOrgao);

        mnuLocalizacao.setText("Localização");

        mniUnidade.setText("Unidade");
        mniUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniUnidadeActionPerformed(evt);
            }
        });
        mnuLocalizacao.add(mniUnidade);
        mnuLocalizacao.add(jSeparator3);

        mniBloco.setText("Bloco");
        mniBloco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBlocoActionPerformed(evt);
            }
        });
        mnuLocalizacao.add(mniBloco);
        mnuLocalizacao.add(jSeparator4);

        mniPiso.setText("Piso");
        mniPiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPisoActionPerformed(evt);
            }
        });
        mnuLocalizacao.add(mniPiso);
        mnuLocalizacao.add(jSeparator5);

        mniSala.setText("Sala");
        mniSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSalaActionPerformed(evt);
            }
        });
        mnuLocalizacao.add(mniSala);

        mnuCadastrar.add(mnuLocalizacao);

        mnuPatrimonio.setText("Patrimônio");

        mniIncluirPatrimonio.setText("Incluir Patrimônio");
        mniIncluirPatrimonio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniIncluirPatrimonioActionPerformed(evt);
            }
        });
        mnuPatrimonio.add(mniIncluirPatrimonio);
        mnuPatrimonio.add(jSeparator1);

        mniTipoSubtipo.setText("Incluir Tipo ou Subtipo");
        mniTipoSubtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTipoSubtipoActionPerformed(evt);
            }
        });
        mnuPatrimonio.add(mniTipoSubtipo);
        mnuPatrimonio.add(jSeparator2);

        mniConservacaoStatus.setText("Incluir Grau de Conservação ou Status");
        mniConservacaoStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniConservacaoStatusActionPerformed(evt);
            }
        });
        mnuPatrimonio.add(mniConservacaoStatus);

        mnuCadastrar.add(mnuPatrimonio);

        mnbPrincipal.add(mnuCadastrar);

        mnuMovimentacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/movimentacao.fw.png"))); // NOI18N
        mnuMovimentacoes.setText("Movimentações");
        mnuMovimentacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuMovimentacoesMouseClicked(evt);
            }
        });
        mnbPrincipal.add(mnuMovimentacoes);

        mnuConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/lupa.png"))); // NOI18N
        mnuConsulta.setText("Consultas");
        mnuConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuConsultaMouseClicked(evt);
            }
        });

        mniConsultaPatrimonio.setText("Patrimônio");
        mniConsultaPatrimonio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mniConsultaPatrimonioMouseClicked(evt);
            }
        });
        mniConsultaPatrimonio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniConsultaPatrimonioActionPerformed(evt);
            }
        });
        mnuConsulta.add(mniConsultaPatrimonio);

        mniConsultaHistórico.setText("Histórico");
        mniConsultaHistórico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mniConsultaHistóricoMouseClicked(evt);
            }
        });
        mniConsultaHistórico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniConsultaHistóricoActionPerformed(evt);
            }
        });
        mnuConsulta.add(mniConsultaHistórico);

        mniConsultaBaixados.setText("Baixado");
        mniConsultaBaixados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mniConsultaBaixadosMouseClicked(evt);
            }
        });
        mniConsultaBaixados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniConsultaBaixadosActionPerformed(evt);
            }
        });
        mnuConsulta.add(mniConsultaBaixados);

        mnbPrincipal.add(mnuConsulta);

        mnuRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/relatorio48.fw.png"))); // NOI18N
        mnuRelatorios.setText("Relatórios");
        mnuRelatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuRelatoriosMouseClicked(evt);
            }
        });
        mnuRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRelatoriosActionPerformed(evt);
            }
        });

        mniRelatorioSala.setText("Salas");
        mniRelatorioSala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mniRelatorioSalaMouseClicked(evt);
            }
        });
        mniRelatorioSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniRelatorioSalaActionPerformed(evt);
            }
        });
        mnuRelatorios.add(mniRelatorioSala);

        mniRelatorioDescricao.setText("Patrimônio");
        mniRelatorioDescricao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mniRelatorioDescricaoMouseClicked(evt);
            }
        });
        mniRelatorioDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniRelatorioDescricaoActionPerformed(evt);
            }
        });
        mnuRelatorios.add(mniRelatorioDescricao);

        mniRelatorioOrgao.setText("Orgão");
        mniRelatorioOrgao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniRelatorioOrgaoActionPerformed(evt);
            }
        });
        mnuRelatorios.add(mniRelatorioOrgao);

        mnbPrincipal.add(mnuRelatorios);

        mnuInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/prancheta.png"))); // NOI18N
        mnuInventario.setText("Inventario");
        mnuInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuInventarioMouseClicked(evt);
            }
        });
        mnbPrincipal.add(mnuInventario);

        mnuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/user.png"))); // NOI18N
        mnuUsuario.setText("Usuário");

        mniMinhaConta.setText("Minha Conta");
        mniMinhaConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mniMinhaContaMouseClicked(evt);
            }
        });
        mniMinhaConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniMinhaContaActionPerformed(evt);
            }
        });
        mnuUsuario.add(mniMinhaConta);

        mniAdicionarUsuario.setText("Gerenciar Usuários");
        mniAdicionarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mniAdicionarUsuarioMouseClicked(evt);
            }
        });
        mniAdicionarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAdicionarUsuarioActionPerformed(evt);
            }
        });
        mnuUsuario.add(mniAdicionarUsuario);

        mnbPrincipal.add(mnuUsuario);

        mnuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/sobre.fw.png"))); // NOI18N
        mnuSobre.setText("Sobre");
        mnuSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuSobreMouseClicked(evt);
            }
        });
        mnbPrincipal.add(mnuSobre);

        setJMenuBar(mnbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniOrgaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniOrgaoActionPerformed
        // TODO add your handling code here:
        OrgaoView entidade = new OrgaoView(usuarioAtivo);
        pnlPrincipal.removeAll();
        entidade.setLocation(pnlPrincipal.getWidth()/2 - entidade.getWidth()/2,pnlPrincipal.getHeight()/2 - entidade.getHeight()/2);
        pnlPrincipal.add(entidade);
        pnlPrincipal.updateUI();
    }//GEN-LAST:event_mniOrgaoActionPerformed

    private void mniIncluirPatrimonioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniIncluirPatrimonioActionPerformed
        // TODO add your handling code here:
        PatrimonioView patrimonio = null;
        try {
            patrimonio = new PatrimonioView(usuarioAtivo);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
        pnlPrincipal.removeAll();
        patrimonio.setLocation(pnlPrincipal.getWidth()/2 - patrimonio.getWidth()/2,pnlPrincipal.getHeight()/2 - patrimonio.getHeight()/2);
        pnlPrincipal.add(patrimonio);
        pnlPrincipal.updateUI();
    }//GEN-LAST:event_mniIncluirPatrimonioActionPerformed

    private void mniTipoSubtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTipoSubtipoActionPerformed
        // TODO add your handling code here:
        TipoSubtipoView tipoSubtipo = new TipoSubtipoView(usuarioAtivo);
        pnlPrincipal.removeAll();
        tipoSubtipo.setLocation(pnlPrincipal.getWidth()/2 - tipoSubtipo.getWidth()/2,pnlPrincipal.getHeight()/2 - tipoSubtipo.getHeight()/2);
        pnlPrincipal.add(tipoSubtipo);
        pnlPrincipal.updateUI();
    }//GEN-LAST:event_mniTipoSubtipoActionPerformed

    private void mniConservacaoStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniConservacaoStatusActionPerformed
        ConservacaoStatusView conservacaoStatus = new ConservacaoStatusView(usuarioAtivo);
        pnlPrincipal.removeAll();
        conservacaoStatus.setLocation(pnlPrincipal.getWidth()/2 - conservacaoStatus.getWidth()/2,pnlPrincipal.getHeight()/2 - conservacaoStatus.getHeight()/2);
        pnlPrincipal.add(conservacaoStatus);
        pnlPrincipal.updateUI();
    }//GEN-LAST:event_mniConservacaoStatusActionPerformed

    private void mniUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniUnidadeActionPerformed
        // TODO add your handling code here:
        UnidadeView unidade = new UnidadeView(usuarioAtivo);
        pnlPrincipal.removeAll();
        unidade.setLocation(pnlPrincipal.getWidth()/2 - unidade.getWidth()/2,pnlPrincipal.getHeight()/2 - unidade.getHeight()/2);
        pnlPrincipal.add(unidade);
        pnlPrincipal.updateUI();
    }//GEN-LAST:event_mniUnidadeActionPerformed

    private void mniBlocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBlocoActionPerformed
        // TODO add your handling code here:
        BlocoView bloco = new BlocoView(usuarioAtivo);
        pnlPrincipal.removeAll();
        bloco.setLocation(pnlPrincipal.getWidth()/2 - bloco.getWidth()/2,pnlPrincipal.getHeight()/2 - bloco.getHeight()/2);
        pnlPrincipal.add(bloco);
        pnlPrincipal.updateUI();
    }//GEN-LAST:event_mniBlocoActionPerformed

    private void mniPisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPisoActionPerformed
        // TODO add your handling code here:
        PisoView piso = new PisoView(usuarioAtivo);
        pnlPrincipal.removeAll();
        piso.setLocation(pnlPrincipal.getWidth()/2 - piso.getWidth()/2,pnlPrincipal.getHeight()/2 - piso.getHeight()/2);
        pnlPrincipal.add(piso);
        pnlPrincipal.updateUI();
    }//GEN-LAST:event_mniPisoActionPerformed

    private void mniSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSalaActionPerformed
        // TODO add your handling code here:
        SalaView sala = new SalaView(usuarioAtivo);
        pnlPrincipal.removeAll();
        sala.setLocation(pnlPrincipal.getWidth()/2 - sala.getWidth()/2,pnlPrincipal.getHeight()/2 - sala.getHeight()/2);
        pnlPrincipal.add(sala);
        pnlPrincipal.updateUI();
    }//GEN-LAST:event_mniSalaActionPerformed

    private void mnuSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuSobreMouseClicked
        SobreView sobre = new SobreView();
        pnlPrincipal.removeAll();
        sobre.setLocation(pnlPrincipal.getWidth()/2 - sobre.getWidth()/2,pnlPrincipal.getHeight()/2 - sobre.getHeight()/2);
        pnlPrincipal.add(sobre);
        pnlPrincipal.updateUI();
    }//GEN-LAST:event_mnuSobreMouseClicked

    private void mniAdicionarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniAdicionarUsuarioMouseClicked
        //sem uso 
    }//GEN-LAST:event_mniAdicionarUsuarioMouseClicked

    private void mniAdicionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAdicionarUsuarioActionPerformed
        UsuarioView usuario = new UsuarioView(usuarioAtivo);
        pnlPrincipal.removeAll();
        usuario.setLocation(pnlPrincipal.getWidth()/2 - usuario.getWidth()/2,pnlPrincipal.getHeight()/2 - usuario.getHeight()/2);
        pnlPrincipal.add(usuario);
        pnlPrincipal.updateUI();
    }//GEN-LAST:event_mniAdicionarUsuarioActionPerformed

    private void mnuRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRelatoriosActionPerformed
       //sem uso
    }//GEN-LAST:event_mnuRelatoriosActionPerformed

    private void mnuRelatoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuRelatoriosMouseClicked
        
    }//GEN-LAST:event_mnuRelatoriosMouseClicked

    private void mnuConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuConsultaMouseClicked
       
    }//GEN-LAST:event_mnuConsultaMouseClicked

    private void mniRelatorioSalaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniRelatorioSalaMouseClicked
        
    }//GEN-LAST:event_mniRelatorioSalaMouseClicked

    private void mniRelatorioDescricaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniRelatorioDescricaoMouseClicked
        
    }//GEN-LAST:event_mniRelatorioDescricaoMouseClicked

    private void mniRelatorioSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniRelatorioSalaActionPerformed
        RelatorioSalaView relatorio = new RelatorioSalaView();
        pnlPrincipal.removeAll();
        relatorio.setLocation(pnlPrincipal.getWidth()/2 - relatorio.getWidth()/2,pnlPrincipal.getHeight()/2 - relatorio.getHeight()/2);
        pnlPrincipal.add(relatorio);
        pnlPrincipal.updateUI();
    }//GEN-LAST:event_mniRelatorioSalaActionPerformed

    private void mniRelatorioDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniRelatorioDescricaoActionPerformed
        RelatorioDescricaoView relatorio = new RelatorioDescricaoView();
        pnlPrincipal.removeAll();
        relatorio.setLocation(pnlPrincipal.getWidth()/2 - relatorio.getWidth()/2,pnlPrincipal.getHeight()/2 - relatorio.getHeight()/2);
        pnlPrincipal.add(relatorio);
        pnlPrincipal.updateUI();
    }//GEN-LAST:event_mniRelatorioDescricaoActionPerformed

    private void mniMinhaContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniMinhaContaMouseClicked
        
    }//GEN-LAST:event_mniMinhaContaMouseClicked

    private void mniMinhaContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniMinhaContaActionPerformed
        MinhaContaView minhaConta = new MinhaContaView(usuarioAtivo);
        pnlPrincipal.removeAll();
        minhaConta.setLocation(pnlPrincipal.getWidth()/2 - minhaConta.getWidth()/2,pnlPrincipal.getHeight()/2 - minhaConta.getHeight()/2);
        pnlPrincipal.add(minhaConta);
        pnlPrincipal.updateUI();
    }//GEN-LAST:event_mniMinhaContaActionPerformed

    private void mnuMovimentacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuMovimentacoesMouseClicked
        MovimentacaoView movimentacao = new MovimentacaoView(usuarioAtivo);
        pnlPrincipal.removeAll();
        movimentacao.setLocation(pnlPrincipal.getWidth()/2 - movimentacao.getWidth()/2,pnlPrincipal.getHeight()/2 - movimentacao.getHeight()/2);
        pnlPrincipal.add(movimentacao);
        pnlPrincipal.updateUI();
    }//GEN-LAST:event_mnuMovimentacoesMouseClicked

    private void mnuInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuInventarioMouseClicked
        InventarioView inventario = new InventarioView();
        pnlPrincipal.removeAll();
        inventario.setLocation(pnlPrincipal.getWidth()/2 - inventario.getWidth()/2,pnlPrincipal.getHeight()/2 - inventario.getHeight()/2);
        pnlPrincipal.add(inventario);
        pnlPrincipal.updateUI();
    }//GEN-LAST:event_mnuInventarioMouseClicked

    private void mniConsultaPatrimonioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniConsultaPatrimonioMouseClicked
       
    }//GEN-LAST:event_mniConsultaPatrimonioMouseClicked

    private void mniConsultaHistóricoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniConsultaHistóricoMouseClicked
        
    }//GEN-LAST:event_mniConsultaHistóricoMouseClicked

    private void mniConsultaBaixadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniConsultaBaixadosMouseClicked
        
    }//GEN-LAST:event_mniConsultaBaixadosMouseClicked

    private void mniConsultaPatrimonioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniConsultaPatrimonioActionPerformed
        ConsultaView consulta = null;
        try {
            consulta = new ConsultaView();
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
        pnlPrincipal.removeAll();
        consulta.setLocation(pnlPrincipal.getWidth()/2 - consulta.getWidth()/2,pnlPrincipal.getHeight()/2 - consulta.getHeight()/2);
        pnlPrincipal.add(consulta);
        pnlPrincipal.updateUI();
    }//GEN-LAST:event_mniConsultaPatrimonioActionPerformed

    private void mniConsultaHistóricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniConsultaHistóricoActionPerformed
       HistoricoView historico=null;
        try {
            historico = new HistoricoView();
            
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
        pnlPrincipal.removeAll();
        historico.setLocation(pnlPrincipal.getWidth()/2 - historico.getWidth()/2,pnlPrincipal.getHeight()/2 - historico.getHeight()/2);
        pnlPrincipal.add(historico);
        pnlPrincipal.updateUI();
    }//GEN-LAST:event_mniConsultaHistóricoActionPerformed

    private void mniConsultaBaixadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniConsultaBaixadosActionPerformed
       BaixadoView baixado = null;
        try {
            baixado = new BaixadoView();
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
        pnlPrincipal.removeAll();
        baixado.setLocation(pnlPrincipal.getWidth()/2 - baixado.getWidth()/2,pnlPrincipal.getHeight()/2 - baixado.getHeight()/2);
        pnlPrincipal.add(baixado);
        pnlPrincipal.updateUI();
    }//GEN-LAST:event_mniConsultaBaixadosActionPerformed

    private void mniRelatorioOrgaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniRelatorioOrgaoActionPerformed
        RelatorioOrgaoView relatorio = new RelatorioOrgaoView();
        pnlPrincipal.removeAll();
        relatorio.setLocation(pnlPrincipal.getWidth()/2 - relatorio.getWidth()/2,pnlPrincipal.getHeight()/2 - relatorio.getHeight()/2);
        pnlPrincipal.add(relatorio);
        pnlPrincipal.updateUI();
    }//GEN-LAST:event_mniRelatorioOrgaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuBar mnbPrincipal;
    private javax.swing.JMenuItem mniAdicionarUsuario;
    private javax.swing.JMenuItem mniBloco;
    private javax.swing.JMenuItem mniConservacaoStatus;
    private javax.swing.JMenuItem mniConsultaBaixados;
    private javax.swing.JMenuItem mniConsultaHistórico;
    private javax.swing.JMenuItem mniConsultaPatrimonio;
    private javax.swing.JMenuItem mniIncluirPatrimonio;
    private javax.swing.JMenuItem mniMinhaConta;
    private javax.swing.JMenuItem mniOrgao;
    private javax.swing.JMenuItem mniPiso;
    private javax.swing.JMenuItem mniRelatorioDescricao;
    private javax.swing.JMenuItem mniRelatorioOrgao;
    private javax.swing.JMenuItem mniRelatorioSala;
    private javax.swing.JMenuItem mniSala;
    private javax.swing.JMenuItem mniTipoSubtipo;
    private javax.swing.JMenuItem mniUnidade;
    private javax.swing.JMenu mnuCadastrar;
    private javax.swing.JMenu mnuConsulta;
    private javax.swing.JMenu mnuInventario;
    private javax.swing.JMenu mnuLocalizacao;
    private javax.swing.JMenu mnuMovimentacoes;
    private javax.swing.JMenu mnuPatrimonio;
    private javax.swing.JMenu mnuRelatorios;
    private javax.swing.JMenu mnuSobre;
    private javax.swing.JMenu mnuUsuario;
    private javax.swing.JDesktopPane pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
